### ISSUE TITLE
[Enhancement] URL variables in routes

### ISSUE THREAD

**Issue by Starwort** [s-cork/HashRouting#6]
I would like a way of mimicking dynamic deep links using routing.

Example:
- `@routing.route('users/{user}', title="{user}'s profile")`
- `user` should be available to the routed form, perhaps in a `self.dynamic_vars` dict or similar
- Would behave similarly to url_dict but allow the developer a form closer to dynamic deep links

I can have a go at implementing this myself, but I cannot guarantee code quality

**Comment by Starwort** [comment]
Ok I had a go and came to the conclusion that I have no idea how this library works

**Comment by s-cork** [comment]
A challenge here is that it should be two way. i.e. it should both set the url and be able to navigate to that page when the url changes. 

Reading a set of parameters is fairly straight forward since we can split by `?`, `&` and `=` (sort of). Then to check a typed url is valid we can simply check whether there is a pattern match and that all the keys match... Reading deep linking and 'unformatting' strings is more challenging. And not quite a case of split by `/`


I did originally have something like this in mind but stopped short because of the effort involved. Figuring that the url 
`#users?user=johndoe` was sufficient for this library. 

Example... unformatting the formatted string. E.g. `articles/page-{id}` is this valid? If it is then we can't split by `/` when reading the typed url. Working out which url path based on the `url_hash` becomes more involved than the current setup. 

And while the above url might be prettier. I didn't come to the conclusion that the prettiness was significant enough when compared with the `url_dict` approach like `articles?page=3`. 

Of course there's a point at which this argument stops. 

I'm happy to provide more explanation on how the library works and point you in the right direction. 

It's certainly possible to implement. Django and flask url paths might be useful inspiration and may have useful source code for reading the url paths.

I think it would be an awesome feature to implement.

**Comment by Starwort** [comment]
> A challenge here is that it should be two way. i.e. it should both set the url and be able to navigate to that page when the url changes. 

I'm not 100% sure what you mean here, doesn't setting as a URL just involve `routing.set_url_hash()`?

> Reading a set of parameters is fairly straight forward since we can split by `?`, `&` and `=` (sort of). Then to check a typed url is valid we can simply check whether there is a pattern match and that all the keys match... Reading deep linking and 'unformatting' strings is more challenging. And not quite a case of split by `/`

This makes sense. I would be ok with forcing dynamic deep links to within `/` though

> I did originally have something like this in mind but stopped short because of the effort involved. Figuring that the url 
> `#users?user=johndoe` was sufficient for this library. 

Haha, that's fair. Hopefully I'll be able to get an implementation you can merge in :)

> Example... unformatting the formatted string. E.g. `articles/page-{id}` is this valid? If it is then we can't split by `/` when reading the typed url. Working out which url path based on the `url_hash` becomes more involved than the current setup. 

In an ideal world, it would be; but that URL could be rewritten as `articles/page/{id}` without losing any real readability imo, and then it would be much easier to detect substituted strings

> And while the above url might be prettier. I didn't come to the conclusion that the prettiness was significant enough when compared with the `url_dict` approach like `articles?page=3`. 

I totally understand this, cost of implementation vs value of feature :)

> I'm happy to provide more explanation on how the library works and point you in the right direction. 

I would very much like to have a go at implementing this, so yes please

> It's certainly possible to implement. Django and flask url paths might be useful inspiration and may have useful source code for reading the url paths. The approach I took is (mostly) inspired by Django and so reading up on the Django's urlpaths will give a general sense of the approach of this library. 

Ahh, *that's* where I remembered it from

> I think it would be an awesome feature to implement. 

Me too! I'll do my best haha

**Comment by s-cork** [comment]
> I'm not 100% sure what you mean here, doesn't setting as a URL just involve `routing.set_url_hash()`?

The user can also change the address bar by typing the `url_hash` and so when that happens you have to be able to handle any url that the user might type. 

The difference here is in the [L99](https://github.com/s-cork/HashRouting/blob/e911eb0365797f0b4ccebc2ba5e2ea323abf7636/client_code/routing.py#L99)
This line gets the url components from the address bar because it was loaded from an address bar change rather than `routing.set_url_hash(...)`.


An extension of this = you have to be able to decode the url hash and then ask the question - _is this url in the list of `_paths`?_

`@routing.route('article/{id}')`
`#article/1` - valid
`#article/foo/1` - not valid

with the current approach (if the user types)
`#article?id=1` valid since we have the correct pattern (`article`) and keys (`['id']`)
`#article?foo=1` not valid since we have a correct pattern but incorrect keys.

For finding the path based on the url components see [L111](https://github.com/s-cork/HashRouting/blob/e911eb0365797f0b4ccebc2ba5e2ea323abf7636/client_code/routing.py#L111)

The current approach is relatively simple for determining a correct path...
```python
if path.url_pattern == url_pattern and set(url_dict) == set(path.url_keys):
      return path
```

If you can figure out how to detect the correct path based on the url then I think you're half way there...


> In an ideal world, it would be; but that URL could be rewritten as articles/page/{id} without losing any real readability imo, and then it would be much easier to detect substituted strings

yes I think this is a sensible restriction.
