### ISSUE TITLE
Instructions on cloning and using the dependency

### ISSUE THREAD

**Issue by subhashb** [s-cork/HashRouting#8]
The [forum post](https://anvil.works/forum/t/hashrouting-routing-navigation-with-url-hash/3949) on HashRouting outlines the thought process and development history of the dependency. It also (presumably) contains the [instruction](https://anvil.works/forum/t/hashrouting-routing-navigation-with-url-hash/3949/40) to use the dependency.

- Are the instructions up-to-date?
- Can they be added to the README here?
- Are there any special instructions if I have a production app already, and want to introduce HashRouting?

I am relatively new to Anvil and would love to use the HashRouting dependency, but I am unsure how to go about it.

Thank you for this dependency!

**Comment by s-cork** [comment]
The readme in this repository is up to date. 

Those instructions on the forum are for updating your existing anvil clone to the latest version for any future changes. 

There is no need to follow those instructions when adding hashrouting for the first time since it will be the latest version. Simply clone the project into your anvil account. Add HashRouting as a dependency to the project you want to use it on. 

Look at the examples and readme and get started. 

Good luck.

**Comment by paloha** [comment]
Hello @subhashb, I had a similar experience as you. Then I've read the readme more carefully, plus I've created a dummy Anvil example to test it out. Now, I have the basic example running. 

- The very first issue was not understanding how dependencies work in Anvil (this was my first time using Anvil).  I solved it by cloning the HashRouting project and setting it as a dependency of my project [according to this](https://anvil.works/docs/deployment/dependencies). @s-cork I think it would be good to mention how to do this in the readme.

- Afterwards, my main issue was not understanding that the use of the `MainForm` is **mandatory**. (Well, at least I believe it is mandatory, although the readme does not say that explicitly).

- The last issue was me not reading carefully and trying to use the **typical method to navigate** (`get_open_form().content_panel.add_component(Form1())`) even though the readme specifically says it is banned.

One thing which is still not clear to me is whether it is possible to achieve standard routing like in Flask, e.g. I want to have a page with this url `<my_domain.com>/contact`. I saw people looking for this in connection to Anvil and this line from readme `@routing.route('article/{id}')` looked like exactly what I wanted but after I made it work there is a hash in front of my contact like so `<my_domain.com>/#contact`. Maybe it would be good to also explicitly say in the readme whether this is possible since more people are asking about it here and there.

**Comment by s-cork** [comment]
thanks for the feedback. Perhaps you can submit a pr with some additions that would have helped you get started.

The original readme was developed in conjunction with another user. Both of us were familiar with anvil so there's certainly areas we may have made assumptions.

re the hash always being there. it's a limitation of anvil i'm afraid. There are feature requests on the forum you might want to like. But essentially that's the reason it's called HashRouting and not Routing 😉 .

**Comment by subhashb** [comment]
@s-cork As an addon-benefit, adding HashRouting to the app visibly improved performance as well 👌  👏

**Comment by s-cork** [comment]
Thanks for the docs updates. 

re performances wins - it's probably the caching that HashRouting does behind the scenes. i.e. if you navigate to the same page you get the same page, rather than creating a new one each time.
